services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: easycab-zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: easycab-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "taxi_positions:1:1,customer_requests:1:1,taxi_status:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  central:
    build:
      context: .
      dockerfile: docker/Dockerfile.central
    container_name: easycab-central
    volumes:
      - ./data:/app/data
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - kafka

  taxi:
    build:
      context: .
      dockerfile: docker/Dockerfile.taxi
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - CENTRAL_HOST=central
      - CENTRAL_PORT=5000
    depends_on:
      - central

  customer:
    build:
      context: .
      dockerfile: docker/Dockerfile.customer
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - ./data/customer_requests:/app/customer_requests
    depends_on:
      - kafka